# Copyright 2010.  BSpoke, LLC.

# AppEngine App Configuration for Cool Geek Jobs

application: coolgeekjobs
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /secure_api/.*
  script: api_handler.py
  login: required
  auth_fail_action: unauthorized
  
- url: /update/jobs
  script: app/updatejob.py
  login: admin
  
- url: /update/joburls
  script: app/updatejob.py
  login: admin

- url: /images
  static_dir: images
   
- url: /js
  static_dir: js
  
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: /web/jobreport.py

- url: /job/session/(.*)
  script: /web/job.py

- url: /user/session/(.*)
  script: /web/user.py
    
- url: /job(.*)
  script: /web/job.py
 
- url: /user(.*)
  script: /web/user.py
  
- url: /morejobs(.*)
  script: /web/jobreport.py

- url: /account(.*)
  script: web/user.py
    
- url: /_admincoolgeeks(.*)
  script: web/admin.py
  login: admin
    
skip_files:
- |
  ^(.*/)?( (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  )$
- .*/tests/.*
- .*_test.py

builtins:
- remote_api: on